[project]
name = "shadow-container-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-search-documents==11.6.0b4",
    "fastapi[standard]>=0.116.1",
    "openai>=1.98.0",
    "semantic-kernel>=1.32.2",
]
